num1=int(input("Enter first number:"))
num2=int(input("Enter second number:"))
sum=num1+num2
difference=num1-num2
product=num1*num2
quotient=num1/num2
remainder=num1%num2
exponent=num1**num2
print(f"Sum : {num1} + {num2} = {sum}")
print(f"Difference : {num1} - {num2} = {difference}")
print(f"Product : {num1} * {num2} = {product}")
print(f"Quotient : {num1} / {num2} = {quotient}")
print(f"Remainder : {num1} % {num2} = {remainder}")
print(f"Exponent : {num1} ** {num2} = {exponent}")
